### PR TITLE
Add a -max_executions flag and config option to limit evaluations

### PR DESCRIPTION
**Pull request by chrisberkhout**
When many pages are available it's handy to be able to set a limit, especially for wrapper scripts.

### CODE REVIEW

**Comment by efd6** [comment]
Sorry, this didn't send a review request. Is there a reason not to reflect the behaviour of the filebeat input and add a `max_executions` field to the config? Is this purely to simulate a `head`?

**Comment by chrisberkhout** [comment]
The idea was to be able to run a single evaluation from the command line.

So needing to supply extra config in a file isn't as good, but having a flag do it just once rather than N times would be just as good.

I did think it was nice to be able to specify `-max 0` and have it do all the checks and setup without actually running it, but that's not so important either.

**Comment by efd6** [comment]
I'm fine with a flag, but since we are doing this, let's also have the config field, with the flag taking precedence.

**Comment by chrisberkhout** [comment]
Sounds good. Named `-max_executions`?

**Comment by efd6** [comment]
Yes, to match the existing filebeat config field.

**Review by efd6 — APPROVED** [review]
Commit message:
```
mito: add max_executions flag and config option to limit evaluations
```

**Pull request merged**
